resources:
  Dbp\Relay\ProxyBundle\ApiPlatform\ProxyData:
    shortName: "ProxyData"
    routePrefix: "/proxy"
    normalizationContext:
      groups: ["ProxyData:output"]
      jsonld_embed_context: true
    denormalizationContext:
      groups: ["ProxyData:input"]

    operations:

      ApiPlatform\Metadata\GetCollection:
        # FIXME: ROLE_SCOPE_API-PROXY is no longer set, this bundle needs to be ported to the new authz system
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_SCOPE_API-PROXY')"
        provider: Dbp\Relay\ProxyBundle\ApiPlatform\ProxyDataProvider
        uriTemplate: "/proxydata"
        openapiContext:
          tags: ["Proxy"]

      ApiPlatform\Metadata\Get:
        # FIXME: ROLE_SCOPE_API-PROXY is no longer set, this bundle needs to be ported to the new authz system
        security: "is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_SCOPE_API-PROXY')"
        provider: Dbp\Relay\ProxyBundle\ApiPlatform\ProxyDataProvider
        uriTemplate: "/proxydata/{identifier}"
        openapiContext:
          tags: ["Proxy"]

      ApiPlatform\Metadata\Post:
        security: "is_granted('IS_AUTHENTICATED_FULLY')"
        processor: Dbp\Relay\ProxyBundle\ApiPlatform\ProxyDataProcessor
        uriTemplate: "/proxydata"
        openapiContext:
          tags: ["Proxy"]
          requestBody:
            content:
              application/json:
                schema:
                  type: "object"

    properties:
      identifier:
        identifier: true
        iri: "http://schema.org/identifier"
      arguments:
      data:
      errors:
      functionName:
      namespace:
