services:
  Dbp\Relay\ProxyBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ProxyBundle\ApiPlatform\:
    resource: '../../ApiPlatform'
    autowire: true
    autoconfigure: true
