services:
  Dbp\Relay\ProxyBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ProxyBundle\DataProvider\ApiPlatform:
    autowire: true
    autoconfigure: true
