services:
  Dbp\Relay\ProxyBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ProxyBundle\DataProvider\ProxyDataProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ProxyBundle\DataPersister\ProxyDataPersister:
    autowire: true
    autoconfigure: true
