services:
  Dbp\Relay\ProxyBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\ProxyBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\ProxyBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true
